version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:4.4
    container_name: syn_mongodb
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: synapp
    volumes:
      - mongodb_data:/data/db
    networks:
      - syn_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL Database
  postgresql:
    image: postgres:15
    container_name: syn_postgresql
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: synapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - syn_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d synapp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: syn_redis
    restart: always
    ports:
      - "6381:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - syn_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # API-Chat Service
  api-chat:
    build:
      context: ./API-Chat
      dockerfile: Dockerfile
    container_name: syn_api_chat
    restart: always
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://root:password123@mongodb:27017/synapp?authSource=admin
      - EYEC_DB=eyeCDB
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./API-Chat:/app
    depends_on:
      - mongodb
      - redis
    networks:
      - syn_network
    healthcheck:
      test: ["CMD", "pgrep", "-f", "chat-service"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API-Get Service
  api-get:
    build:
      context: ./API-Get
      dockerfile: Dockerfile
    container_name: syn_api_get
    restart: always
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://root:password123@mongodb:27017/synapp?authSource=admin
      - EYEC_DB=eyeCDB
      - POSTGRESQL_URL=postgres://postgres:password123@postgresql:5432/synapp?sslmode=disable
    depends_on:
      - mongodb
      - postgresql
    networks:
      - syn_network
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f get-service"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API-Token Service
  api-token:
    build:
      context: ./API-Token
      dockerfile: Dockerfile
    container_name: syn_api_token
    restart: always
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://root:password123@mongodb:27017/synapp?authSource=admin
      - EYEC_DB=eyeCDB
      - POSTGRESQL_URL=postgres://postgres:password123@postgresql:5432/synapp?sslmode=disable
      - REDIS_URL=redis:6379
      - DB_HOST=postgresql
      - DB_USER=postgres
      - DB_PASSWORD=password123
      - DB_NAME=synapp
      - DB_PORT=5432
    depends_on:
      - mongodb
      - postgresql
      - redis
    networks:
      - syn_network
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f api-token || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API-UsersGo Service
  api-usersgo:
    build:
      context: ./API-UsersGo
      dockerfile: Dockerfile
      target: build-env
    container_name: syn_api_usersgo
    restart: always
    ports:
      - "3004:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://root:password123@mongodb:27017/synapp?authSource=admin
      - EYEC_DB=eyeCDB
      - POSTGRESQL_URL=postgres://postgres:password123@postgresql:5432/synapp?sslmode=disable
      - REDIS_URL=redis:6379
      - DB_HOST=postgresql
      - DB_USER=postgres
      - DB_PASSWORD=password123
      - DB_NAME=synapp
      - DB_PORT=5432
    depends_on:
      - mongodb
      - postgresql
      - redis
    networks:
      - syn_network
    healthcheck:
      test: ["CMD", "pgrep", "-f", "main", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API-Upload Service
  api-upload:
    build:
      context: ./API-Upload
      dockerfile: Dockerfile
    container_name: syn_api_upload
    restart: always
    ports:
      - "3005:3004"
    environment:
      - PORT=3004
      - MONGODB_URI=mongodb://root:password123@mongodb:27017/synapp?authSource=admin
      - MEDIADIR=/app/media      # Add this line
      - STREAMDIR=/app/streams   # Add this line
    volumes:
      - media_files:/app/media      # Add these lines
      - stream_files:/app/streams   # Add these lines
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - syn_network
    healthcheck:
      test: ["CMD", "pgrep", "-f", "upload-service", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API-UploadV2 Service
  api-uploadv2:
    build:
      context: ./API-UploadV2
      dockerfile: Dockerfile
    container_name: syn_api_uploadv2
    restart: always
    ports:
      - "3006:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://root:password123@mongodb:27017/synapp?authSource=admin
      - POSTGRESQL_URL=postgres://postgres:password123@postgresql:5432/synapp?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - MEDIADIR=/app/media          # Add this line
      - STREAMDIR=/app/streams       # Add this line
      - INIT_MEDIA_DIR=/app/media    # Add this line
      - BASE_URL=http://162.0.230.105:3006  # Add this line for correct screenshot URL generation
      - AWS_ACCESS_KEY_ID=AKIA5JYOFS6PAMV7TA5B
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=eu-north-1
    volumes:
      - media_files:/app/media       # Add these lines
      - stream_files:/app/streams    # Add these lines
    depends_on:
      mongodb:
        condition: service_healthy
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - syn_network
    healthcheck:
      test: ["CMD", "pgrep", "-f", "api-uploadv2", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API-Notifications Service (Background service)
  api-notifications:
    build:
      context: ./API-Notifications
      dockerfile: Dockerfile
    container_name: syn_api_notifications
    restart: always
    environment:
      - MONGODB_URI=mongodb://root:password123@mongodb:27017/synapp?authSource=admin
      - EYEC_DB=eyeCDB
      - REDIS_URL=redis://redis:6379
      - NOTIFICATION_CHANNEL=notifications
    depends_on:
      - mongodb
      - redis
    networks:
      - syn_network
    healthcheck:
      test: ["CMD", "pgrep", "-f", "notification-service", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Syn-API-Live Service (Background service)
  syn-api-live:
    build:
      context: ./Syn-API-Live
      dockerfile: Dockerfile
    container_name: syn_api_live
    restart: always
    ports:
      - "1935:1935"
    environment:
      - MONGODB_URI=mongodb://root:password123@mongodb:27017/synapp?authSource=admin
      - EYEC_DB=eyeCDB
    volumes:
      - ./Syn-API-Live/script:/app/script
      - /mnt/storage:/mnt/storage
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - syn_network
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f nginx || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: syn_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - media_files:/app/media:rw       # Fixed: Changed from ro to rw for write access
      - stream_files:/app/streams:rw    # Fixed: Changed from ro to rw for write access
      - /mnt/storage:/mnt/storage:ro    # Legacy media storage for old videos
    depends_on:
      - api-chat
      - api-get
      - api-token
      - api-usersgo
      - api-upload
      - api-uploadv2
    networks:
      - syn_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
  postgresql_data:
  redis_data:
  media_files:     # Add this line
  stream_files:    # Add this line

networks:
  syn_network:
    driver: bridge
